# Generated by Django 5.2.4 on 2025-07-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
