# Generated by Django 5.2.4 on 2025-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dareexchange_deadline_dareexchange_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='feedback',
            field=models.CharField(default=1234567890, max_length=400),
            preserve_default=False,
        ),
    ]
