# Generated by Django 5.2.4 on 2025-07-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dareexchange_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dareexchange',
            name='feedback',
        ),
    ]
