# Generated by Django 5.2.4 on 2025-07-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_dareexchange_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='dare_image',
            field=models.ImageField(blank=True, null=True, upload_to='dare_images/'),
        ),
    ]
